title: Braden Murray
logo: img_1_1695758445688.jpg
# description: Data Analyst with two years of experience and MSc in Data analytics/ Business Intelligence. 
# show_downloads: false
<br><br>
<a href="www.linkedin.com/in/brady-murray-703bab274">LinkedIn</a>
theme: jekyll-theme-minimal
