title: Braden Murray
logo: img_1_1695758445688.jpg
# description: Data Analyst with two years of experience and MSc in Data analytics/ Business Intelligence. 
# show_downloads: false
theme: jekyll-theme-minimal
